apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: instavote-prod
  namespace: argo-cd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: instavote
  source:
    kustomize:
      namespace: prod
    path: prod
    repoURL: https://github.com/kasunsjc/argo-labs
    targetRevision: release
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true